version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      babel:
        patterns:
          - '@babel/*'
    reviewers:
      - '@ExpediaGroup/cypress-codegen-admins'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    reviewers:
      - '@ExpediaGroup/cypress-codegen-admins'
