/*
Copyright 2022 Expedia, Inc.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    https://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

import { parse } from '@babel/parser';
import * as t from '@babel/types';
import generate from '@babel/generator';
import { readFileSync } from 'fs';
import { resolve } from 'path';
import { format, Options } from 'prettier';

export const generateContentWithImports = async (filePath: string, prettierConfig: Options) => {
  const contents = readFileSync(resolve(filePath)).toString();
  const ast = parse(contents, { sourceType: 'module', plugins: ['typescript'] });
  const currentNodes = ast.program.body;
  const importsExist = contents.includes('* Generated by cypress-codegen *');
  if (importsExist) {
    return contents;
  }
  const { code: existingCode } = generate(t.program(currentNodes), { retainLines: true });
  const newImportStatement = generateImportStatement();
  const { code: newCode } = generate(t.program(newImportStatement));
  const resultingCode = `${existingCode}\n\n${newCode}\n`;
  return await format(resultingCode, {
    parser: 'babel-ts',
    ...prettierConfig
  });
};

const generateImportStatement = () => {
  const importExpression = t.callExpression(t.identifier('import'), [
    t.stringLiteral('../commands')
  ]);

  const cypressExpression = t.memberExpression(
    t.memberExpression(t.identifier('Cypress'), t.identifier('Commands')),
    t.identifier('addAll')
  );
  const fullExpression = t.callExpression(
    t.memberExpression(importExpression, t.identifier('then')),
    [cypressExpression]
  );

  const importStatement = t.expressionStatement(fullExpression);
  t.addComment(importStatement, 'leading', '* Generated by cypress-codegen *');

  return [importStatement];
};
