/*
Copyright 2022 Expedia, Inc.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    https://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

import { generateExports } from '../src/generate-exports';

const filePaths = [
  'cypress/commands/file/path/1.tsx',
  'cypress/commands/file/path/2.tsx',
  'cypress/commands/filePath/3.ts'
];
const prettierConfig = {
  singleQuote: true,
  printWidth: 90
};

describe('generateExports', () => {
  it('should generate exports file', async () => {
    const result = await generateExports(filePaths, prettierConfig);
    expect(result).toEqual(`/** Generated by cypress-codegen **/
export * from './file/path/1';
export * from './file/path/2';
export * from './filePath/3';
`);
  });
});
