name: Release

on:
  pull_request:
    #  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Setup node and pnpm cache
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install
        run: pnpm install

      - run: echo //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }} >> .npmrc

      - run: pnpm publish --recursive --no-git-checks
#      - name: Create Release
#        run: pnpm semantic-release --no-ci
#        env:
#          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
#          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
