name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Lint and Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install
        run: bun install

      - name: Lint
        run: bun lint

      - name: Unit Tests
        run: bun run test
  cli:
    name: CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install
        run: bun install

      - name: Install and setup bin
        run: bun setup-cli

      - name: Run cypress-codegen
        run: |
          bun cypress-codegen --testingType component
          bun cypress-codegen --testingType e2e

      - name: Check generated types match git
        run: |
          if [[ $(git status --porcelain) ]]; then
            echo "Detected changes in generated types"
            git status
            exit 1
          fi
  component:
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Component Integration
            component: true
          - name: E2E Integration
            component: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install
        run: bun install

      - name: Integration Tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          build: bun run build
          browser: chrome
          component: ${{ matrix.component }}
