name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Lint and Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Setup node and pnpm cache
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Unit Tests
        run: pnpm test
  cli:
    name: CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Setup node and pnpm cache
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install and setup bin
        run: pnpm setup-cli

      - name: Run cypress-codegen
        run: |
          pnpm cypress-codegen --testingType component
          pnpm cypress-codegen --testingType e2e

      - name: Check generated types match git
        run: |
          if [[ $(git status --porcelain) ]]; then
            echo "Detected changes in generated types"
            git status
            exit 1
          fi
  component:
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Component Integration
            component: true
          - name: E2E Integration
            component: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Setup node and pnpm cache
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install
        run: pnpm install && pnpm cypress install

      - name: Integration Tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          build: pnpm build
          browser: chrome
          component: ${{ matrix.component }}
