name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Build and Test
    runs-on: eg-default
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Unit Tests
        run: npm run test

      - name: Integration Tests
        run: npm run cypress
